In [5]:
import pandas as pd


# Read the data
df = pd.read_csv('aggregate.csv')

mean = df.groupby(['method', 'num_subject', 'num_room', 'num_conflict', 'status'])['duration'].mean()

In [6]:
mean

method  num_subject  num_room  num_conflict  status
cp      10           2         4             4           0.490843
                               12            4           2.409427
                               24            4           0.153329
                               40            2         120.068878
                                             4           5.688557
        16           3         12            2         120.160805
                                             4         110.340600
                               24            4          26.632833
                               40            4          29.865355
                               60            4           2.058233
        20           4         24            2         120.241795
                                             4          22.627694
                               40            2         120.347286
                                             4          31.651297
                               60            2         120.261674
                                             4           4.925989
                               80            2         120.269979
                                             4           2.328538
        30           6         40            2         120.663605
                                             4          14.647132
                               60            2         120.792796
                               80            2         120.872537
                                             4           2.735702
        40           8         60            2         121.952816
                               80            2         121.912181
                               120           2         121.857140
                                             4           4.344822
        50           10        80            2         123.159703
                               120           2         122.978829
mip     10           2         4             0           0.298319
                               12            0           0.523224
                               24            0           0.542741
                               40            0           1.073381
        16           3         12            0           3.975832
                               24            0           4.459830
                               40            0           4.990055
                               60            0          70.161171
        20           4         24            0         103.456999
                               40            0          11.839481
                                             1         118.238517
                               60            0          27.370772
                               80            0          10.589451
                                             1         119.736174
        30           6         40            0          15.316012
                                             1         114.182618
                               60            1         117.854555
                               80            0          62.583215
                                             1         118.403720
        40           8         60            0          66.676349
                                             1         102.942015
                               80            1         109.988449
                               120           0          42.301635
                                             1         116.667446
        50           10        80            1          98.516138
                                             6         105.964589
                               120           1         108.302788
Name: duration, dtype: float64

In [7]:
mean.to_csv('mean.csv')

In [20]:
import numpy as np
mean = pd.read_csv('mean.csv')
mean['status'] = np.where((mean['method'] == 'cp') & (mean['status'] == 2), 1, mean['status'])
mean['status'] = np.where((mean['method'] == 'cp') & (mean['status'] == 4), 0, mean['status'])

In [21]:
sucess_solve = mean[mean['status'] == 0]

In [22]:
sucess_solve

   method  num_subject  num_room  num_conflict  status    duration
0      cp           10         2             4       0    0.490843
1      cp           10         2            12       0    2.409427
2      cp           10         2            24       0    0.153329
4      cp           10         2            40       0    5.688557
6      cp           16         3            12       0    9.340600
7      cp           16         3            24       0   26.632833
8      cp           16         3            40       0   29.865355
9      cp           16         3            60       0    2.058233
11     cp           20         4            24       0   22.627694
13     cp           20         4            40       0   31.651297
15     cp           20         4            60       0    4.925989
17     cp           20         4            80       0    2.328538
19     cp           30         6            40       0   14.647132
22     cp           30         6            80       0    2.735702
26     cp           40         8           120       0    4.344822
29    mip           10         2             4       0    0.298319
30    mip           10         2            12       0    0.523224
31    mip           10         2            24       0    0.542741
32    mip           10         2            40       0    1.073381
33    mip           16         3            12       0    3.975832
34    mip           16         3            24       0    4.459830
35    mip           16         3            40       0    4.990055
36    mip           16         3            60       0   70.161171
37    mip           20         4            24       0  103.456999
38    mip           20         4            40       0   11.839481
40    mip           20         4            60       0   27.370772
41    mip           20         4            80       0   10.589451
43    mip           30         6            40       0   15.316012
46    mip           30         6            80       0   62.583215
48    mip           40         8            60       0   66.676349
51    mip           40         8           120       0   42.301635

In [23]:
sucess_solve.to_csv('mip-cp-result.csv')